version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: sms_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: cyprusre123
      POSTGRES_DB: Sms_Service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sms_network

volumes:
  postgres_data:

networks:
  sms_network:
